/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AAppExpr6 extends PExpr6
{
    private PApp2 _app2_;

    public AAppExpr6()
    {
        // Constructor
    }

    public AAppExpr6(
        @SuppressWarnings("hiding") PApp2 _app2_)
    {
        // Constructor
        setApp2(_app2_);

    }

    @Override
    public Object clone()
    {
        return new AAppExpr6(
            cloneNode(this._app2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAppExpr6(this);
    }

    public PApp2 getApp2()
    {
        return this._app2_;
    }

    public void setApp2(PApp2 node)
    {
        if(this._app2_ != null)
        {
            this._app2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._app2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._app2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._app2_ == child)
        {
            this._app2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._app2_ == oldChild)
        {
            setApp2((PApp2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
