/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ABlocIbloc extends PIbloc
{
    private TLAcc _lAcc_;
    private PLi _li_;
    private TRAcc _rAcc_;

    public ABlocIbloc()
    {
        // Constructor
    }

    public ABlocIbloc(
        @SuppressWarnings("hiding") TLAcc _lAcc_,
        @SuppressWarnings("hiding") PLi _li_,
        @SuppressWarnings("hiding") TRAcc _rAcc_)
    {
        // Constructor
        setLAcc(_lAcc_);

        setLi(_li_);

        setRAcc(_rAcc_);

    }

    @Override
    public Object clone()
    {
        return new ABlocIbloc(
            cloneNode(this._lAcc_),
            cloneNode(this._li_),
            cloneNode(this._rAcc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlocIbloc(this);
    }

    public TLAcc getLAcc()
    {
        return this._lAcc_;
    }

    public void setLAcc(TLAcc node)
    {
        if(this._lAcc_ != null)
        {
            this._lAcc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lAcc_ = node;
    }

    public PLi getLi()
    {
        return this._li_;
    }

    public void setLi(PLi node)
    {
        if(this._li_ != null)
        {
            this._li_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._li_ = node;
    }

    public TRAcc getRAcc()
    {
        return this._rAcc_;
    }

    public void setRAcc(TRAcc node)
    {
        if(this._rAcc_ != null)
        {
            this._rAcc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rAcc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lAcc_)
            + toString(this._li_)
            + toString(this._rAcc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lAcc_ == child)
        {
            this._lAcc_ = null;
            return;
        }

        if(this._li_ == child)
        {
            this._li_ = null;
            return;
        }

        if(this._rAcc_ == child)
        {
            this._rAcc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lAcc_ == oldChild)
        {
            setLAcc((TLAcc) newChild);
            return;
        }

        if(this._li_ == oldChild)
        {
            setLi((PLi) newChild);
            return;
        }

        if(this._rAcc_ == oldChild)
        {
            setRAcc((TRAcc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
