/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AFctVar extends PVar
{
    private TId _id_;
    private TLCroc _lCroc_;
    private PE _e_;
    private TRCroc _rCroc_;

    public AFctVar()
    {
        // Constructor
    }

    public AFctVar(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TLCroc _lCroc_,
        @SuppressWarnings("hiding") PE _e_,
        @SuppressWarnings("hiding") TRCroc _rCroc_)
    {
        // Constructor
        setId(_id_);

        setLCroc(_lCroc_);

        setE(_e_);

        setRCroc(_rCroc_);

    }

    @Override
    public Object clone()
    {
        return new AFctVar(
            cloneNode(this._id_),
            cloneNode(this._lCroc_),
            cloneNode(this._e_),
            cloneNode(this._rCroc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFctVar(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TLCroc getLCroc()
    {
        return this._lCroc_;
    }

    public void setLCroc(TLCroc node)
    {
        if(this._lCroc_ != null)
        {
            this._lCroc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lCroc_ = node;
    }

    public PE getE()
    {
        return this._e_;
    }

    public void setE(PE node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    public TRCroc getRCroc()
    {
        return this._rCroc_;
    }

    public void setRCroc(TRCroc node)
    {
        if(this._rCroc_ != null)
        {
            this._rCroc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rCroc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._lCroc_)
            + toString(this._e_)
            + toString(this._rCroc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._lCroc_ == child)
        {
            this._lCroc_ = null;
            return;
        }

        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        if(this._rCroc_ == child)
        {
            this._rCroc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._lCroc_ == oldChild)
        {
            setLCroc((TLCroc) newChild);
            return;
        }

        if(this._e_ == oldChild)
        {
            setE((PE) newChild);
            return;
        }

        if(this._rCroc_ == oldChild)
        {
            setRCroc((TRCroc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
