/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALireExpr6 extends PExpr6
{
    private TLire _lire_;

    public ALireExpr6()
    {
        // Constructor
    }

    public ALireExpr6(
        @SuppressWarnings("hiding") TLire _lire_)
    {
        // Constructor
        setLire(_lire_);

    }

    @Override
    public Object clone()
    {
        return new ALireExpr6(
            cloneNode(this._lire_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALireExpr6(this);
    }

    public TLire getLire()
    {
        return this._lire_;
    }

    public void setLire(TLire node)
    {
        if(this._lire_ != null)
        {
            this._lire_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lire_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lire_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lire_ == child)
        {
            this._lire_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lire_ == oldChild)
        {
            setLire((TLire) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
