/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALLdvo extends PLdvo
{
    private PLdv _ldv_;

    public ALLdvo()
    {
        // Constructor
    }

    public ALLdvo(
        @SuppressWarnings("hiding") PLdv _ldv_)
    {
        // Constructor
        setLdv(_ldv_);

    }

    @Override
    public Object clone()
    {
        return new ALLdvo(
            cloneNode(this._ldv_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALLdvo(this);
    }

    public PLdv getLdv()
    {
        return this._ldv_;
    }

    public void setLdv(PLdv node)
    {
        if(this._ldv_ != null)
        {
            this._ldv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ldv_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ldv_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ldv_ == child)
        {
            this._ldv_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ldv_ == oldChild)
        {
            setLdv((PLdv) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
