/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ANbrE6 extends PE6
{
    private TNbr _nbr_;

    public ANbrE6()
    {
        // Constructor
    }

    public ANbrE6(
        @SuppressWarnings("hiding") TNbr _nbr_)
    {
        // Constructor
        setNbr(_nbr_);

    }

    @Override
    public Object clone()
    {
        return new ANbrE6(
            cloneNode(this._nbr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANbrE6(this);
    }

    public TNbr getNbr()
    {
        return this._nbr_;
    }

    public void setNbr(TNbr node)
    {
        if(this._nbr_ != null)
        {
            this._nbr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nbr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nbr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nbr_ == child)
        {
            this._nbr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nbr_ == oldChild)
        {
            setNbr((TNbr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
