/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ANegationExpr5 extends PExpr5
{
    private TNegation _negation_;
    private PExpr5 _expr5_;

    public ANegationExpr5()
    {
        // Constructor
    }

    public ANegationExpr5(
        @SuppressWarnings("hiding") TNegation _negation_,
        @SuppressWarnings("hiding") PExpr5 _expr5_)
    {
        // Constructor
        setNegation(_negation_);

        setExpr5(_expr5_);

    }

    @Override
    public Object clone()
    {
        return new ANegationExpr5(
            cloneNode(this._negation_),
            cloneNode(this._expr5_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegationExpr5(this);
    }

    public TNegation getNegation()
    {
        return this._negation_;
    }

    public void setNegation(TNegation node)
    {
        if(this._negation_ != null)
        {
            this._negation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._negation_ = node;
    }

    public PExpr5 getExpr5()
    {
        return this._expr5_;
    }

    public void setExpr5(PExpr5 node)
    {
        if(this._expr5_ != null)
        {
            this._expr5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr5_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._negation_)
            + toString(this._expr5_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._negation_ == child)
        {
            this._negation_ = null;
            return;
        }

        if(this._expr5_ == child)
        {
            this._expr5_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._negation_ == oldChild)
        {
            setNegation((TNegation) newChild);
            return;
        }

        if(this._expr5_ == oldChild)
        {
            setExpr5((PExpr5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
