/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AOuE extends PE
{
    private PE _e_;
    private TOu _ou_;
    private PE1 _e1_;

    public AOuE()
    {
        // Constructor
    }

    public AOuE(
        @SuppressWarnings("hiding") PE _e_,
        @SuppressWarnings("hiding") TOu _ou_,
        @SuppressWarnings("hiding") PE1 _e1_)
    {
        // Constructor
        setE(_e_);

        setOu(_ou_);

        setE1(_e1_);

    }

    @Override
    public Object clone()
    {
        return new AOuE(
            cloneNode(this._e_),
            cloneNode(this._ou_),
            cloneNode(this._e1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOuE(this);
    }

    public PE getE()
    {
        return this._e_;
    }

    public void setE(PE node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    public TOu getOu()
    {
        return this._ou_;
    }

    public void setOu(TOu node)
    {
        if(this._ou_ != null)
        {
            this._ou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ou_ = node;
    }

    public PE1 getE1()
    {
        return this._e1_;
    }

    public void setE1(PE1 node)
    {
        if(this._e1_ != null)
        {
            this._e1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._e_)
            + toString(this._ou_)
            + toString(this._e1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        if(this._ou_ == child)
        {
            this._ou_ = null;
            return;
        }

        if(this._e1_ == child)
        {
            this._e1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._e_ == oldChild)
        {
            setE((PE) newChild);
            return;
        }

        if(this._ou_ == oldChild)
        {
            setOu((TOu) newChild);
            return;
        }

        if(this._e1_ == oldChild)
        {
            setE1((PE1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
