/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class APProg extends PProg
{
    private PLdvo2 _ldvo2_;
    private PLdf _ldf_;

    public APProg()
    {
        // Constructor
    }

    public APProg(
        @SuppressWarnings("hiding") PLdvo2 _ldvo2_,
        @SuppressWarnings("hiding") PLdf _ldf_)
    {
        // Constructor
        setLdvo2(_ldvo2_);

        setLdf(_ldf_);

    }

    @Override
    public Object clone()
    {
        return new APProg(
            cloneNode(this._ldvo2_),
            cloneNode(this._ldf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPProg(this);
    }

    public PLdvo2 getLdvo2()
    {
        return this._ldvo2_;
    }

    public void setLdvo2(PLdvo2 node)
    {
        if(this._ldvo2_ != null)
        {
            this._ldvo2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ldvo2_ = node;
    }

    public PLdf getLdf()
    {
        return this._ldf_;
    }

    public void setLdf(PLdf node)
    {
        if(this._ldf_ != null)
        {
            this._ldf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ldf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ldvo2_)
            + toString(this._ldf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ldvo2_ == child)
        {
            this._ldvo2_ = null;
            return;
        }

        if(this._ldf_ == child)
        {
            this._ldf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ldvo2_ == oldChild)
        {
            setLdvo2((PLdvo2) newChild);
            return;
        }

        if(this._ldf_ == oldChild)
        {
            setLdf((PLdf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
