/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ARetourI extends PI
{
    private PIr _ir_;

    public ARetourI()
    {
        // Constructor
    }

    public ARetourI(
        @SuppressWarnings("hiding") PIr _ir_)
    {
        // Constructor
        setIr(_ir_);

    }

    @Override
    public Object clone()
    {
        return new ARetourI(
            cloneNode(this._ir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARetourI(this);
    }

    public PIr getIr()
    {
        return this._ir_;
    }

    public void setIr(PIr node)
    {
        if(this._ir_ != null)
        {
            this._ir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ir_ == child)
        {
            this._ir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ir_ == oldChild)
        {
            setIr((PIr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
