/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASinonIsi extends PIsi
{
    private TSi _si_;
    private PExpr _expr_;
    private TAlors _alors_;
    private PIbloc _l1_;
    private TSinon _sinon_;
    private PIbloc _l2_;

    public ASinonIsi()
    {
        // Constructor
    }

    public ASinonIsi(
        @SuppressWarnings("hiding") TSi _si_,
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") TAlors _alors_,
        @SuppressWarnings("hiding") PIbloc _l1_,
        @SuppressWarnings("hiding") TSinon _sinon_,
        @SuppressWarnings("hiding") PIbloc _l2_)
    {
        // Constructor
        setSi(_si_);

        setExpr(_expr_);

        setAlors(_alors_);

        setL1(_l1_);

        setSinon(_sinon_);

        setL2(_l2_);

    }

    @Override
    public Object clone()
    {
        return new ASinonIsi(
            cloneNode(this._si_),
            cloneNode(this._expr_),
            cloneNode(this._alors_),
            cloneNode(this._l1_),
            cloneNode(this._sinon_),
            cloneNode(this._l2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASinonIsi(this);
    }

    public TSi getSi()
    {
        return this._si_;
    }

    public void setSi(TSi node)
    {
        if(this._si_ != null)
        {
            this._si_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._si_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public TAlors getAlors()
    {
        return this._alors_;
    }

    public void setAlors(TAlors node)
    {
        if(this._alors_ != null)
        {
            this._alors_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alors_ = node;
    }

    public PIbloc getL1()
    {
        return this._l1_;
    }

    public void setL1(PIbloc node)
    {
        if(this._l1_ != null)
        {
            this._l1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._l1_ = node;
    }

    public TSinon getSinon()
    {
        return this._sinon_;
    }

    public void setSinon(TSinon node)
    {
        if(this._sinon_ != null)
        {
            this._sinon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sinon_ = node;
    }

    public PIbloc getL2()
    {
        return this._l2_;
    }

    public void setL2(PIbloc node)
    {
        if(this._l2_ != null)
        {
            this._l2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._l2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._si_)
            + toString(this._expr_)
            + toString(this._alors_)
            + toString(this._l1_)
            + toString(this._sinon_)
            + toString(this._l2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._si_ == child)
        {
            this._si_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._alors_ == child)
        {
            this._alors_ = null;
            return;
        }

        if(this._l1_ == child)
        {
            this._l1_ = null;
            return;
        }

        if(this._sinon_ == child)
        {
            this._sinon_ = null;
            return;
        }

        if(this._l2_ == child)
        {
            this._l2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._si_ == oldChild)
        {
            setSi((TSi) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._alors_ == oldChild)
        {
            setAlors((TAlors) newChild);
            return;
        }

        if(this._l1_ == oldChild)
        {
            setL1((PIbloc) newChild);
            return;
        }

        if(this._sinon_ == oldChild)
        {
            setSinon((TSinon) newChild);
            return;
        }

        if(this._l2_ == oldChild)
        {
            setL2((PIbloc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
