/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TTantq extends Token
{
    public TTantq()
    {
        super.setText("tantque");
    }

    public TTantq(int line, int pos)
    {
        super.setText("tantque");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTantq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTantq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTantq text.");
    }
}
