/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.node;

import src.analysis.*;

@SuppressWarnings("nls")
public final class AAffectationI extends PI
{
    private PIa _ia_;

    public AAffectationI()
    {
        // Constructor
    }

    public AAffectationI(
        @SuppressWarnings("hiding") PIa _ia_)
    {
        // Constructor
        setIa(_ia_);

    }

    @Override
    public Object clone()
    {
        return new AAffectationI(
            cloneNode(this._ia_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAffectationI(this);
    }

    public PIa getIa()
    {
        return this._ia_;
    }

    public void setIa(PIa node)
    {
        if(this._ia_ != null)
        {
            this._ia_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ia_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ia_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ia_ == child)
        {
            this._ia_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ia_ == oldChild)
        {
            setIa((PIa) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
