/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.node;

import src.analysis.*;

@SuppressWarnings("nls")
public final class AAppfoncI extends PI
{
    private PIaf _iaf_;

    public AAppfoncI()
    {
        // Constructor
    }

    public AAppfoncI(
        @SuppressWarnings("hiding") PIaf _iaf_)
    {
        // Constructor
        setIaf(_iaf_);

    }

    @Override
    public Object clone()
    {
        return new AAppfoncI(
            cloneNode(this._iaf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAppfoncI(this);
    }

    public PIaf getIaf()
    {
        return this._iaf_;
    }

    public void setIaf(PIaf node)
    {
        if(this._iaf_ != null)
        {
            this._iaf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._iaf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._iaf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._iaf_ == child)
        {
            this._iaf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._iaf_ == oldChild)
        {
            setIaf((PIaf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
