/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.node;

import src.analysis.*;

@SuppressWarnings("nls")
public final class AEcrireI extends PI
{
    private PIecr _iecr_;

    public AEcrireI()
    {
        // Constructor
    }

    public AEcrireI(
        @SuppressWarnings("hiding") PIecr _iecr_)
    {
        // Constructor
        setIecr(_iecr_);

    }

    @Override
    public Object clone()
    {
        return new AEcrireI(
            cloneNode(this._iecr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEcrireI(this);
    }

    public PIecr getIecr()
    {
        return this._iecr_;
    }

    public void setIecr(PIecr node)
    {
        if(this._iecr_ != null)
        {
            this._iecr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._iecr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._iecr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._iecr_ == child)
        {
            this._iecr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._iecr_ == oldChild)
        {
            setIecr((PIecr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
