/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.node;

import src.analysis.*;

@SuppressWarnings("nls")
public final class AIaf extends PIaf
{
    private PAff _aff_;

    public AIaf()
    {
        // Constructor
    }

    public AIaf(
        @SuppressWarnings("hiding") PAff _aff_)
    {
        // Constructor
        setAff(_aff_);

    }

    @Override
    public Object clone()
    {
        return new AIaf(
            cloneNode(this._aff_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIaf(this);
    }

    public PAff getAff()
    {
        return this._aff_;
    }

    public void setAff(PAff node)
    {
        if(this._aff_ != null)
        {
            this._aff_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aff_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aff_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aff_ == child)
        {
            this._aff_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aff_ == oldChild)
        {
            setAff((PAff) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
