/* This file was generated by SableCC (http://www.sablecc.org/). */

package src.node;

import src.analysis.*;

@SuppressWarnings("nls")
public final class AVideDv1 extends PDv1
{

    public AVideDv1()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AVideDv1();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVideDv1(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
